/** See https://betterprogramming.pub/how-to-secure-angular-environment-variables-for-use-in-github-actions-39c07587d590 */
/* tslint:disable */
/* eslint-disable */
const { writeFile, existsSync, mkdirSync } = require("fs");
const { argv } = require("yargs");

require("dotenv").config();
const environment = argv.environment;

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== "") {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

// Providing path to the `environments` directory
const envDirectory = "./src/environments";

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

//creates the `environment.prod.ts` and `environment.ts` file if it does not exist
writeFileUsingFS("./src/environments/environment.prod.ts", "");
writeFileUsingFS("./src/environments/environment.ts", "");

// Workflow only runs in prod for this project, no checks required here
const isProduction = true;

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? "./src/environments/environment.prod.ts"
  : "./src/environments/environment.ts";

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: ${isProduction},
    APP_ID: '${process.env.APP_ID}'
  };
`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file

/* tslint:enable */
